### ISSUE TITLE
Create MVC 6 UI Project

### ISSUE THREAD

**Issue by MisterJames** [ClearMeasureLabs/ClearMeasureBootcamp#5]
This one will be a bigger effort.  On the list to consider:
- Convert selectlist providers to view services
- Convert todo bits to view components, possibly rename
- Use commands/queries instead of repositories (could use MediatR here)
- Consider EF7 (can be used with dnx core)
- Consider EF6 (can be used with full dotnet on 4.6)
- Make ApplicationInformation static or cached
- Consider the default DI in MVC6 - (AutoFac, perhaps?)
- Bits from #6 (Project Tidy Up)
- Update packages

**Comment by MisterJames** [comment]
In progress on the branch trail starting from the 4.6 multitargeting (https://github.com/ClearMeasureLabs/ClearMeasureBootcamp/tree/refactor/move-to46-with-multitargetting)

**Comment by jeffreypalermo** [comment]
deferred until release
