### ISSUE TITLE
Add CD Assets For Scriptable Deployment

### ISSUE THREAD

**Issue by MisterJames** [ClearMeasureLabs/ClearMeasureBootcamp#9]
Implement as "infrastructure as code"

The theme here is in creating a set of scripts that can be used to not only put initial infrastructure in place, but also to support adding new elements to existing projects, particularly how it fits with regards to microservices vs. monolithic applications. 

Assets should be composable, customizable in the context of a given project and able to provision not only deployment environment concerns, but also standing up repositories, build services and various forms of testing (ie. a/b, canary, gated automatic deployment).

**Comment by jeffreypalermo** [comment]
CD is now implemented.  closing this issue.
